### ISSUE TITLE
Documentation on how to run tests results in error

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-taf#306]
When following the instructions in ./docs/edgex-taf.md, at step 4, when running python3 -m TUC --exclude Skipped --include deploy-base-service -u deploy.robot -p default, the result is the following error:

INFO:root:Run testing for profile 'default'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jim/.local/lib/python3.6/site-packages/TUC/__main__.py", line 10, in <module>
    trigger.start()
  File "/home/jim/.local/lib/python3.6/site-packages/TUC/trigger.py", line 140, in start
    run_robot(args)
  File "/home/jim/.local/lib/python3.6/site-packages/TUC/trigger.py", line 153, in run_robot
    setup_config(args)
  File "/home/jim/.local/lib/python3.6/site-packages/TUC/trigger.py", line 102, in setup_config
    constant = __import__("TAF.config.global_variables", fromlist=['global_variables'])
ModuleNotFoundError: No module named 'TAF'

For clarity sake, here is the env setup
jim@jim-ubuntu:~/forks/edgex-taf/TAF/utils/scripts/docker$ env |grep ARCH
ARCH=x86_64
jim@jim-ubuntu:~/forks/edgex-taf/TAF/utils/scripts/docker$ env |grep SECURITY
SECURITY_SERVICE_NEEDED=false
jim@jim-ubuntu:~/forks/edgex-taf/TAF/utils/scripts/docker$ env |grep USE_DB
USE_DB=redis
jim@jim-ubuntu:~/forks/edgex-taf/TAF/utils/scripts/docker$

**Comment by jinlinGuan** [comment]
Should run the command in the directory of edgex-taf.

**Comment by jpwhitemn** [comment]
thanks @jinlinGuan
